### ISSUE TITLE
Adjust order of Asset fields

### ISSUE THREAD

**Issue by ryanlrussell** [p1up/sonicwall_firewall#1]
Since this is the first issue I'm filing with you, please allow me to introduce myself.

I'm Ryan Russell with Phantom. Thanks so much for the SonicWALL App, that's awesome! Very happy to have the contribution.

We usually do a light review on new Apps for Phantom to see if there are any suggestions we can make. I have a couple for you, if you're interested in some possible improvements.

SonicWALL App 1.2.9

This one is pretty cosmetic. Most of the Apps we have done are set up to have the IP/hostname field first, and then username and password second and third. We will also sometimes add a spacer to make the layout look a little better, so that username and password are on the same line.

Here's how yours lays out currently:

![screen shot 2016-07-26 at 6 05 50 pm](https://cloud.githubusercontent.com/assets/1728937/17161661/27bd5bc0-5364-11e6-9600-a940f9f10f9e.png)

Ideally, we'd like to see something similar to these:
![screen shot 2016-07-26 at 6 59 26 pm](https://cloud.githubusercontent.com/assets/1728937/17161675/4303f8a8-5364-11e6-8d17-c31d7d739824.png)
![screen shot 2016-07-26 at 6 59 42 pm](https://cloud.githubusercontent.com/assets/1728937/17161678/49cd4b12-5364-11e6-9b4f-42ae8d542968.png)

You can specify the field order in the JSON. And there is a little bit of a trick in the last example, we added a spacer field that doesn't show.

The JSON snippet for the last one looks like this:
    "configuration": {
      "device": {
        "data_type": "string",
        "order": 0,
        "description": "Device IP/Hostname",
        "required": true
      },
      "ph": {
        "data_type": "ph",
        "order": 1
      },
      "username": {
        "data_type": "string",
        "order": 2,
        "description": "Username",
        "required": true
      },
      "password": {
        "data_type": "password",
        "order": 3,
        "description": "Password",
        "required": true
      }

Notice the "order" fields, and the "ph" parameter, which stands for placeholder. With no description or data-type, it's invisible, and forces username and password to the next line.

With a similar change, yours would look something like:
    "configuration": {
          "firewall_mgmt": {
            "description": "Management IP/Hostname of Sonicwall Firewall",
            "data_type": "string",
            "order": 0,
            "required": true
          },
          "ph": {
            "data_type": "ph",
            "order": 1
          },
          "admin_account": {
            "description": "Administrator's username",
            "data_type": "string",
            "order": 2,
            "required": true
          },
          "admin_password": {
            "description": "Administrator's password",
            "data_type": "password",
            "order": 3,
            "required": true
          }
          },

**Comment by p1up** [comment]
Thanks so much. I've just update the json file to include this enhance.
