### ISSUE TITLE
Add some "contains"

### ISSUE THREAD

**Issue by ryanlrussell** [p1up/sonicwall_firewall#2]
SonicWALL App 1.2.9

I looks like none of your action parameters currently have a "contains" value. For example, your unblock ip action:

{
        "action" : "unblock ip",
        "description": "Unblock an ip",
        "type" : "correct",
        "identifier": "unblock_ip",
        "read_only": false,
        "parameters": {
            "target": {
                "description": "IP address to unblock",
                "data_type": "string",
                "contains": [],
                "primary": true,
                "required": true
            }

Adding a contains type for certain parameters will greatly enhance how parts of the Phantom UI work with your App, and make things convenient for Phantom users.

The "contains" value is how Phantom knows that an Artifact or output value from another action will work as input to one of your actions. For example, if I have an IP address in Mission Control, I can get a list of Actions that take an IP address as an Action parameter. It looks like this:

![screen shot 2016-07-26 at 7 24 48 pm](https://cloud.githubusercontent.com/assets/1728937/17162004/e49d912c-5366-11e6-9ad0-9904629ea5f6.png)

Because I have (other) assets that provide a block ip action that takes an IP parameter, I get the "block ip" action in the context menu for an IP address. But when I continue, SonicWALL will be missing from the list of Assets that take an IP as a context item:

![screen shot 2016-07-26 at 7 25 53 pm](https://cloud.githubusercontent.com/assets/1728937/17162033/1962b4e6-5367-11e6-8d0e-2494d08f2645.png)

If I change your JSON so that the block ip action has a contains field, like so:

```
  {
            "action": "block ip",
            "description": "Block an IP",
            "type" : "contain",
            "identifier": "block_ip",
            "read_only": false,
            "parameters": {
                    "target": {
                            "description": "IP address to block",
                            "data_type": "string",
                            "contains": [ "ip" ],
                            "primary": true,
                            "required": true
                    }
            },
```

Then SonicWALL Assets are now in the list:

![screen shot 2016-07-26 at 7 30 20 pm](https://cloud.githubusercontent.com/assets/1728937/17162071/739897be-5367-11e6-8731-46d0873f4649.png)

Note that "contains" takes a list of strings, which can of course just be a list of one string if that's all that's needed. Other Apps might need both "ip" and "hostname" as contains types for some parameters, but I think all of yours take just ip.

For your App, looks like you would want to use the following types:

"contains": [ "ip" ],
"contains": [ "url" ],
"contains": [ "network application" ],

For both the block and unblock actions. 

Also, I forgot to mention it in the other issue I filed, but if you make any changes, please remember to bump your version number up. Thanks!

I don't think I have anything else. Really clean first rev!

**Comment by p1up** [comment]
Add the "ip", "url" and "port" in "contains". did not add the "network application" because the "protocol" filed only accepts "TCP" or "UDP". Might not fit the "network application".
